---
- job:
    name: application-service-pipeline
    project-type: pipeline
    pipeline:
      script-path: Jenkinsfile
      scm:
        - git:
            url: "https://github.com/anperez78/application-service.git"
            branches:
              - master
